routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\NewsController;


Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::view('/contacto', 'contact')->name('contact');

Route::get('/blog', [PostController::class, 'index'])->name('posts.index');
Route::get('/blog/create', [PostController::class, 'create'])->name('posts.create');
Route::post('/blog', [PostController::class, 'store'])->name('posts.store');

Route::get('/blog/{post}', [PostController::class, 'show'])->name('posts.show');
Route::get('/blog/{post}/edit', [PostController::class, 'edit'])->name('posts.edit');
Route::patch('/blog/{post}', [PostController::class, 'update'])->name('posts.update');
Route::delete('/blog/{post}',[PostController::class, 'destroy'])->name('posts.destroy');


Route::view('/about', 'about')->name('about');

Route::view('/login', 'auth.login')->name('login');
Route::post('/login', [AuthenticatedSessionController::class, 'store']);
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');


Route::view('/register', 'auth.register')->name('register');
Route::post('/register', [RegisteredUserController::class, 'store']);

Route::resource('news', NewsController::class);

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;
    protected $guarded = ['_token'];
    protected $fillable = ['title', 'resume', 'author'];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\News;


class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $news = News::all();
        return view('news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('news.create');
    }

    /**
     * Store a newly created resource in storage.
     */
   public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'resume' => 'required|string',
            'author' => 'required|string|max:255',
        ]);

        News::create([
            'title' => $request->title,
            'resume' => $request->resume,
            'author' => $request->author,
        ]);

        return redirect()->route('news.index')
                        ->with('success', 'News created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $newsItem = News::findOrFail($id);
        return view('news.show', compact('newsItem'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $newsItem = News::findOrFail($id);
        return view('news.edit', compact('newsItem'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'resume' => 'required|string',
            'author' => 'required|string|max:255',
        ]);

        $newsItem = News::findOrFail($id);

        // Especificar los campos para actualizar
        $newsItem->update($request->only(['title', 'resume', 'author']));

        return redirect()->route('news.index')
                        ->with('success', 'News updated successfully.');
    }


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $newsItem = News::findOrFail($id);
        $newsItem->delete();

        return redirect()->route('news.index')
                        ->with('success', 'News deleted successfully.');
    }
}

resources/views/news/create.blade.php
@extends('layaouts\app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-xl font-bold my-4">Crear Noticia</h1>
    <form method="POST" action="{{ route('news.store') }}" class="w-full max-w-lg">
        @csrf
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label for="title" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Título</label>
                <input type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="title" name="title" required>
            </div>
            <div class="w-full px-3">
                <label for="resume" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Resumen</label>
                <textarea class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="resume" name="resume" rows="3" required></textarea>
            </div>
            <div class="w-full px-3">
                <label for="author" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Autor</label>
                <input type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="author" name="author" required>
            </div>
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Guardar Noticia</button>
        <a href="{{ route('news.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancelar</a>
    </form>
</div>
@endsection

resources/views/news/edit.blade.php
@extends('layaouts\app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-xl font-bold my-4">Editar Noticia</h1>
    <form method="POST" action="{{ route('news.update', $newsItem->id) }}" class="w-full max-w-lg">
        @csrf
        @method('PUT')
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label for="title" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Título</label>
                <input type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white" id="title" name="title" value="{{ $newsItem->title }}" required>
            </div>
            <div class="w-full px-3">
                <label for="resume" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Resumen</label>
                <textarea class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="resume" name="resume" rows="3" required>{{ $newsItem->resume }}</textarea>
            </div>
            <div class="w-full px-3">
                <label for="author" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Autor</label>
                <input type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="author" name="author" value="{{ $newsItem->author }}" required>
            </div>
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Actualizar Noticia</button>
        <a href="{{ route('news.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancelar</a>
    </form>
</div>
@endsection

resources/views/news/index.blade.php
@extends('layaouts\app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-xl font-bold my-4">Noticias</h1>
    @auth
        <a href="{{ route('news.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Crear Noticia</a>
    @endauth
    <div class="mt-3">
        <ul class="list-disc">
            @foreach ($news as $new)
                <li class="mt-2 p-3 shadow-md rounded">
                    {{ $new->title }} - <small>{{ $new->author }}</small>
                    <a href="{{ route('news.show', $new->id) }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded text-xs ml-2">Ver</a>

                    @auth
                        <a href="{{ route('news.edit', $new->id) }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded text-xs">Editar</a>
                    <a href="{{ route('news.destroy', $new->id) }}"
                    class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded text-xs"
                    onclick="event.preventDefault(); if(confirm('¿Estás seguro de querer eliminar esta noticia?')) this.nextElementSibling.submit();">
                        Eliminar
                    </a>
                    <form action="{{ route('news.destroy', $new->id) }}" method="POST" class="hidden">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="text-xs text-red-600">Eliminar</button>
                    </form>
                    @endauth
                </li>
            @endforeach
        </ul>
    </div>
</div>
@endsection

resources/views/news/show.blade.php
@extends('layaouts\app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-xl font-bold my-4">{{ $newsItem->title }}</h1>
    <p class="mb-4">{{ $newsItem->resume }}</p>
    <p class="text-sm font-light mb-4 text-end">Autor: {{ $newsItem->author }}</p>
    <a href="{{ route('news.index') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">Volver a la lista</a>
</div>
@endsection